export const EASY_WORDS = [
  "APPLE", "WATER", "HOUSE", "PARTY", "NIGHT", "DREAM", "SMILE", "MOUSE", "CLOCK", "CHAIR",
  "TABLE", "MONEY", "PAPER", "STONE", "BLOOD", "EARTH", "LUNCH", "DANCE", "MAGIC", "QUEEN"
];

export const MEDIUM_WORDS = [
  "TRAIN", "MUSIC", "PLANT", "SHARK", "BRAIN", "LIGHT", "HEART", "GHOST", "WORLD", "POWER",
  "SPACE", "STORM", "RIVER", "BREAD", "FRUIT", "SUGAR", "STORY", "WOMAN", "CHILD", "BROWN",
  "BLACK", "WHITE", "GREEN", "PENNY", "SNOWY", "FLAME", "CHIEF", "CROWN", "FAITH", "GLORY",
  "HONOR", "NOVEL", "PEACE", "RIGHT", "SOUND", "TRUST", "VOICE", "YOUTH", "ZEBRA", "ALIEN",
  "BERRY", "CANDY", "DONUT", "EAGLE", "FROST", "GRAPE", "HONEY", "IGLOO", "JUMBO", "KITE",
  "LEMON", "MELON", "NINJA", "ONION", "PIZZA", "QUICK", "ROBOT", "STEAK", "TIGER"
];

export const HARD_WORDS = [
  "ABYSS", "BLITZ", "XYLEM", "COVEN", "DIRGE", "EPOCH", "FJORD", "GLYPH", "HAZEL", "IDYLL",
  "JAZZY", "KARMA", "LEMUR", "MACAW", "NEXUS", "OZONE", "PYGMY", "QUART", "RAVEN", "SPHINX",
  "TOPAZ", "UMBRA", "VORTEX", "WALTZ", "YACHT", "ZESTY", "CYNIC", "ENVOY", "FLAIR", "GAUZE"
];
